use_frameworks!

platform :ios, '8.0'
install! 'cocoapods', disable_input_output_paths: true
target 'MyLibrary_Example' do
  pod 'JDLiMyLibrary', :path => '../'

  target 'MyLibrary_Tests' do
    inherit! :search_paths

#    pod 'Kiwi'
#    pod 'FBSnapshotTestCase'
  end
end
